Add php8.3 support for Codecrafters Redis challenge
codecrafters-io/build-your-own-redis pull request #166
Opened 2024-04-02 16:07 UTC by helomair

I kept the older versions in comment in codecrafters.yml, since the older versions are still available

2024-04-03 01:36 UTC, helomair commented
I was wondering whether I should add composer install commands to Dockerfile, since it generates it's own autoload and I saw users use their self made autoloads.

2024-04-09 22:07 UTC, rohitpaulk requested changes
Hey @helomair! 

Sorry for the delay, I've scheduled the test run now.

This is almost there - added one comment re: removing the old version from `codecrafters.yml`. There's also a docker lint failure here: 

<img width="814" alt="Screenshot 2024-04-09 at 23 06 21" src="https://github.com/codecrafters-io/build-your-own-redis/assets/3893573/a0296aeb-50c6-4752-86c1-0f234fede38a">

2024-04-10 02:55 UTC, helomair commented on compiled_starters/php/codecrafters.yml
> +# Available versions: php-7.4 php-8.3
Got it!

2024-04-10 08:29 UTC, rohitpaulk approved these changes

2024-04-10 08:29 UTC, merged