feat: add scala support to redis challenge.
codecrafters-io/build-your-own-redis pull request #173
Opened 2024-04-12 16:54 UTC by ryan-gang

2024-04-13 23:07 UTC, rohitpaulk commented on solutions/scala/01-init/code/spawn_redis_server.sh
> +# sbt reload
@ryan-gang how will this work for users locally?

2024-04-13 23:07 UTC, rohitpaulk requested changes
Question added

2024-04-16 11:05 UTC, ryan-gang commented
Updated the `spawn_redis_server.sh` script, and added a line in the dockerfile to comment them out while running it on test runners.

2024-04-16 11:22 UTC, rohitpaulk approved these changes

2024-04-19 07:39 UTC, merged